name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# cancel previous workflows, run only one workflow
concurrency:
  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dimaslanjaka/proxies-grabber
        submodules: recursive
        token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Setup GitHub
      run: |
        git config --local user.email "dimaslanjaka@gmail.com"
        git config --local user.name "dimaslanjaka"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Cache multiple paths
      uses: actions/cache@v3
      with:
        path: |
          ./databases
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Install Global Dependencies
      run: npm i -g npm gulp-cli typescript ts-node
    - name: Build
      run: |
        yarn
        yarn build
        gulp docs
    - run: echo "" > docs/.nojekyll
      name: +.nojekyll
    - name: Init new repo in dist folder and commit generated files
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '16.x'
      run: |
        cd docs
        git init
        git remote add origin https://github.com/dimaslanjaka/proxies-grabber.git
        git branch -m gh-pages
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'
        git push origin gh-pages